const TENANT_CUSTOMER_BASE_PATH = '/tenant/customers';
const TENANT_CUSTOMER_ITEM_PATH = '/tenant/customers/:customer_id';
const TENANT_CUSTOMER_BASIC_PATH = '/tenant/customers/:customer_id/basic';
const TENANT_CUSTOMER_REALNAME_PATH = '/tenant/customers/:customer_id/realname';
const TENANT_CUSTOMER_OPERATION_LOG_PATH =
  '/tenant/customers/:customer_id/operation-logs';

const TENANT_CUSTOMER_LIST_ROUTE_KEY = 'GET /tenant/customers';
const TENANT_CUSTOMER_CREATE_ROUTE_KEY = 'POST /tenant/customers';
const TENANT_CUSTOMER_DETAIL_ROUTE_KEY = 'GET /tenant/customers/:customer_id';
const TENANT_CUSTOMER_UPDATE_BASIC_ROUTE_KEY =
  'PATCH /tenant/customers/:customer_id/basic';
const TENANT_CUSTOMER_UPDATE_REALNAME_ROUTE_KEY =
  'PATCH /tenant/customers/:customer_id/realname';
const TENANT_CUSTOMER_OPERATION_LOG_ROUTE_KEY =
  'GET /tenant/customers/:customer_id/operation-logs';

const TENANT_CUSTOMER_VIEW_PERMISSION_CODE = 'tenant.customer_management.view';
const TENANT_CUSTOMER_OPERATE_PERMISSION_CODE =
  'tenant.customer_management.operate';
const TENANT_CUSTOMER_SCOPE_MY_VIEW_PERMISSION_CODE =
  'tenant.customer_scope_my.view';
const TENANT_CUSTOMER_SCOPE_MY_OPERATE_PERMISSION_CODE =
  'tenant.customer_scope_my.operate';
const TENANT_CUSTOMER_SCOPE_ASSIST_VIEW_PERMISSION_CODE =
  'tenant.customer_scope_assist.view';
const TENANT_CUSTOMER_SCOPE_ASSIST_OPERATE_PERMISSION_CODE =
  'tenant.customer_scope_assist.operate';
const TENANT_CUSTOMER_SCOPE_ALL_VIEW_PERMISSION_CODE =
  'tenant.customer_scope_all.view';
const TENANT_CUSTOMER_SCOPE_ALL_OPERATE_PERMISSION_CODE =
  'tenant.customer_scope_all.operate';
const TENANT_CUSTOMER_SCOPE = 'tenant';

module.exports = {
  TENANT_CUSTOMER_BASE_PATH,
  TENANT_CUSTOMER_ITEM_PATH,
  TENANT_CUSTOMER_BASIC_PATH,
  TENANT_CUSTOMER_REALNAME_PATH,
  TENANT_CUSTOMER_OPERATION_LOG_PATH,
  TENANT_CUSTOMER_LIST_ROUTE_KEY,
  TENANT_CUSTOMER_CREATE_ROUTE_KEY,
  TENANT_CUSTOMER_DETAIL_ROUTE_KEY,
  TENANT_CUSTOMER_UPDATE_BASIC_ROUTE_KEY,
  TENANT_CUSTOMER_UPDATE_REALNAME_ROUTE_KEY,
  TENANT_CUSTOMER_OPERATION_LOG_ROUTE_KEY,
  TENANT_CUSTOMER_VIEW_PERMISSION_CODE,
  TENANT_CUSTOMER_OPERATE_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE_MY_VIEW_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE_MY_OPERATE_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE_ASSIST_VIEW_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE_ASSIST_OPERATE_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE_ALL_VIEW_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE_ALL_OPERATE_PERMISSION_CODE,
  TENANT_CUSTOMER_SCOPE
};
