const TENANT_SESSION_CONVERSATION_INGEST_PATH =
  '/tenant/sessions/conversations/ingest';
const TENANT_SESSION_HISTORY_INGEST_PATH =
  '/tenant/sessions/history/ingest';
const TENANT_SESSION_CHAT_LIST_PATH =
  '/tenant/sessions/chats';
const TENANT_SESSION_CHAT_MESSAGES_PATH =
  '/tenant/sessions/chats/:conversation_id/messages';
const TENANT_SESSION_ACCOUNT_OPTIONS_PATH =
  '/tenant/sessions/account-options';
const TENANT_SESSION_MESSAGE_CREATE_PATH =
  '/tenant/sessions/messages';
const TENANT_SESSION_OUTBOUND_PULL_PATH =
  '/tenant/sessions/outbound-messages/pull';
const TENANT_SESSION_OUTBOUND_STATUS_PATH =
  '/tenant/sessions/outbound-messages/status';

const TENANT_SESSION_CONVERSATION_INGEST_ROUTE_KEY =
  'POST /tenant/sessions/conversations/ingest';
const TENANT_SESSION_HISTORY_INGEST_ROUTE_KEY =
  'POST /tenant/sessions/history/ingest';
const TENANT_SESSION_CHAT_LIST_ROUTE_KEY =
  'GET /tenant/sessions/chats';
const TENANT_SESSION_CHAT_MESSAGES_ROUTE_KEY =
  'GET /tenant/sessions/chats/:conversation_id/messages';
const TENANT_SESSION_ACCOUNT_OPTIONS_ROUTE_KEY =
  'GET /tenant/sessions/account-options';
const TENANT_SESSION_MESSAGE_CREATE_ROUTE_KEY =
  'POST /tenant/sessions/messages';
const TENANT_SESSION_OUTBOUND_PULL_ROUTE_KEY =
  'GET /tenant/sessions/outbound-messages/pull';
const TENANT_SESSION_OUTBOUND_STATUS_ROUTE_KEY =
  'POST /tenant/sessions/outbound-messages/status';

const TENANT_SESSION_VIEW_PERMISSION_CODE = 'tenant.session_management.view';
const TENANT_SESSION_OPERATE_PERMISSION_CODE = 'tenant.session_management.operate';
const TENANT_SESSION_SCOPE_MY_VIEW_PERMISSION_CODE = 'tenant.session_scope_my.view';
const TENANT_SESSION_SCOPE_ASSIST_VIEW_PERMISSION_CODE =
  'tenant.session_scope_assist.view';
const TENANT_SESSION_SCOPE_ALL_VIEW_PERMISSION_CODE = 'tenant.session_scope_all.view';
const TENANT_SESSION_SCOPE = 'tenant';

module.exports = {
  TENANT_SESSION_CONVERSATION_INGEST_PATH,
  TENANT_SESSION_HISTORY_INGEST_PATH,
  TENANT_SESSION_CHAT_LIST_PATH,
  TENANT_SESSION_CHAT_MESSAGES_PATH,
  TENANT_SESSION_ACCOUNT_OPTIONS_PATH,
  TENANT_SESSION_MESSAGE_CREATE_PATH,
  TENANT_SESSION_OUTBOUND_PULL_PATH,
  TENANT_SESSION_OUTBOUND_STATUS_PATH,
  TENANT_SESSION_CONVERSATION_INGEST_ROUTE_KEY,
  TENANT_SESSION_HISTORY_INGEST_ROUTE_KEY,
  TENANT_SESSION_CHAT_LIST_ROUTE_KEY,
  TENANT_SESSION_CHAT_MESSAGES_ROUTE_KEY,
  TENANT_SESSION_ACCOUNT_OPTIONS_ROUTE_KEY,
  TENANT_SESSION_MESSAGE_CREATE_ROUTE_KEY,
  TENANT_SESSION_OUTBOUND_PULL_ROUTE_KEY,
  TENANT_SESSION_OUTBOUND_STATUS_ROUTE_KEY,
  TENANT_SESSION_VIEW_PERMISSION_CODE,
  TENANT_SESSION_OPERATE_PERMISSION_CODE,
  TENANT_SESSION_SCOPE_MY_VIEW_PERMISSION_CODE,
  TENANT_SESSION_SCOPE_ASSIST_VIEW_PERMISSION_CODE,
  TENANT_SESSION_SCOPE_ALL_VIEW_PERMISSION_CODE,
  TENANT_SESSION_SCOPE
};
